application: organizer-python-758
version: 1
runtime: python27
api_version: 1
threadsafe: true    

handlers:
- url: /u
  static_dir: index
- url: /img
  static_dir: img
- url: /.*
  secure: optional
  script: main.APP


libraries:
- name: webapp2
  version: latest
