application: organizer-python-758
version: 1
runtime: python27
api_version: 1
threadsafe: true    

handlers:
- url: /.*
  secure: always
  script: main.APP

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest